name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Run fmt
        run: deno task fmt:check

      - name: Run lint
        run: deno task lint:check

      - name: Run test
        run: deno task test

  publish_npm:
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Build package
        run: deno task build:npm

      - name: Check version
        id: check
        run: git 

      - name: Publish package to NPM
        run: cd npm && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc && npm publish --new-version ${{steps.check.outputs.version}} --non-interactive
