name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Run format check
        run: deno task format:check

      - name: Run lint check
        run: deno task lint:check

      - name: Run test
        run: deno task test

  publish_npm:
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Get latest tag
        id: tag
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

      - name: Has version changed
        id: version_changed
        run: |
          if git diff --quiet "${{steps.tag.outputs.version}}" HEAD -- VERSION; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Build package
        if: steps.version_changed.outputs.changed == 'true'
        run: deno task build:npm

      - name: Publish package to NPM
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          cd npm 
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          npm publish
