name: on push or pr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - name: Run format check
        run: deno task format:check

      - name: Run lint check
        run: deno task lint:check

      - name: Run test
        run: deno task test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - name: Build package
        run: deno task build:npm

  publish_npm:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - name: Get tags
        id: tag
        run: |
          echo "::set-output name=latest::$(git describe --tags --abbrev=0)"
          echo "::set-output name=new::$(cat VERSION)"

      - name: Has version changed
        id: version_changed
        run: |
          if git diff --quiet "${{steps.tag.outputs.latest}}" HEAD -- VERSION; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Build package
        if: steps.version_changed.outputs.changed == 'true'
        run: deno task build:npm

      - name: Publish release
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          git tag -a ${{steps.tag.outputs.new}} -m "${{steps.tag.outputs.new}}"
          git push --tags
